### ISSUE TITLE
levelui does not support windows?

### ISSUE THREAD

**Issue by thinkerou** [heapwolf/levelui#45]
thanks.

**Comment by kcomplexes** [comment]
I have attached an image of the program running on Windows (launched by dragging the apps folder into the electron launch window). The app is unresponsive to user input (mouse, keyboard), with the exception of the upper textbox which can be resized and typed into.
![windows](https://cloud.githubusercontent.com/assets/16506704/12316074/16284aba-baca-11e5-92ba-544dbb6147a3.png)

**Comment by simon-p-r** [comment]
Yes it works on Windows

**Comment by fukgoo** [comment]
I had the same issue where the app was unresponsive and jumbled. It was solved by rebuilding native modules the easy way with electron-rebuild. [How to Install Native Modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)

Install electron-rebuild:
`npm install --save-dev electron-rebuild`

After installing levelui, run:
`.\node_modules\.bin\electron-rebuild.cmd`

Unfortunately, I have the following error related to the comparator, which prevents it from loading the database.

> [3884:0612/035939:INFO:CONSOLE(141)] "Uncaught OpenError: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator", source: events.js (141)

**Comment by Venryx** [comment]
I had the same issue of the app's UI being unresponsive, due to overlapping UI elements and such.

The solution by @fukgoo didn't work for me, as I hit this error when running `electron-rebuild`:
```
Could not detect abi for version 0.28.3 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

Anyway, since that fix didn't work, I tried finding some other way; I discovered the UI issue is just because the UI's initialization code is not getting run, due to it encountering an error during startup. (I discovered this by remove the `frame: false` part from `index.js`, then opening the Developer Tools through the View menu)

The root error was that one of the `level` modules was apparently not loading properly.

I remembered a note in the readme about it: https://github.com/heapwolf/levelui#development

However, running those post-install commands failed for me, since Windows does not have the `env` command. For me, I just cut out the `env` part, and tried running the `node-gyp` part. However, that failed due to `node-gyp` not being installed. I installed it using: `npm install -g node-gyp`. Then the rebuild command succeeded, at which point running `npm run start` (in the repo root) had the application start successfully, without the console error or the resulting UI issue.

Anyway, complete instructions to install+run on Windows:
1) Clone/download repo to disk.
2) Make sure the version of node you have installed is Node 8 or under -- else you get these install errors: https://github.com/heapwolf/levelui/issues/55. (I use [nvm for windows](https://github.com/coreybutler/nvm-windows) to manage which version of node I'm using.)
3) Run `npm install`.
4) Run `cd node_modules/level`.
5) Run `npm install -g node-gyp`, if `node-gyp` is not yet installed globally.
6) Run `node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell`. (or whatever [the latest readme instructions](https://github.com/heapwolf/levelui#development) say -- except without the `env ... &&` part.
7) Run `cd ../..` to return to the repo root.
8) Run `npm run start`.

If you still are getting issues, edit `index.js`, and remove the `, frame: false` part from the end of the `new BrowserWindow(...)` line, then relaunch. Then open `View->Toggle Developer Tools`, and see what the error is in the console.

**Comment by jrao1** [comment]
I believe in step 4, you need to cd into leveldown directory, not level directory. (Or maybe we need to rebuild both, at least I needed to rebuild leveldown too)
